// This file was generated by tauri-specta. Do not edit this file manually.
// @ts-check
// This file uses strict TypeScript settings to ensure type safety.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async prelogin(request: PreloginRequest) : Promise<Result<PreloginResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prelogin", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Process login with master password
 */
async loginWithPassword(request: LoginRequest) : Promise<Result<LoginResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("login_with_password", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unlock vault with master password
 */
async unlockWithPassword(request: UnlockRequest) : Promise<Result<UnlockResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock_with_password", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Setup new account with master password
 */
async setupAccount(request: SetupAccountRequest) : Promise<Result<SetupAccountResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("setup_account", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lock the vault
 */
async lockVault(userId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("lock_vault", { userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Logout user
 */
async logout(userId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("logout", { userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Refresh access token
 */
async refreshToken(refreshToken: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_token", { refreshToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change master password
 */
async changeMasterPassword(userId: string, currentPassword: string, newPassword: string, email: string, kdfConfig: KdfConfig) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_master_password", { userId, currentPassword, newPassword, email, kdfConfig }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Setup biometric unlock
 */
async setupBiometricUnlock(userId: string, userKey: number[]) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("setup_biometric_unlock", { userId, userKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unlock with biometric authentication
 */
async unlockWithBiometric(request: BiometricUnlockRequest) : Promise<Result<BiometricUnlockResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock_with_biometric", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all ciphers for a user
 */
async getAllCiphers(request: GetCiphersRequest) : Promise<Result<CipherView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_ciphers", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a cipher
 */
async saveCipher(request: SaveCipherRequest) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_cipher", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a cipher
 */
async deleteCipher(request: DeleteCipherRequest) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_cipher", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search ciphers
 */
async searchCiphers(request: SearchCiphersRequest) : Promise<Result<CipherView[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_ciphers", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get folders for a user
 */
async getFolders(request: GetFoldersRequest) : Promise<Result<Folder[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_folders", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a folder
 */
async saveFolder(request: SaveFolderRequest) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_folder", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a folder
 */
async deleteFolder(request: DeleteFolderRequest) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_folder", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get collections for an organization
 */
async getCollections(request: GetCollectionsRequest) : Promise<Result<Collection[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_collections", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all available server providers
 */
async getAllServerProviders() : Promise<Result<ServerProvider[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_server_providers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current active server provider
 */
async getCurrentServerProvider() : Promise<Result<ServerProvider | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_server_provider") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get server provider information for frontend
 */
async getServerProviderInfo() : Promise<Result<ServerProviderInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_server_provider_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a new custom server provider
 */
async addCustomServerProvider(request: AddCustomProviderRequest) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_custom_server_provider", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a new custom server provider with custom URLs
 */
async addCustomServerProviderWithUrls(request: AddCustomProviderWithUrlsRequest) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_custom_server_provider_with_urls", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update an existing server provider
 */
async updateServerProvider(request: UpdateProviderRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_server_provider", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the current active server provider
 */
async setCurrentServerProvider(request: SetCurrentProviderRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_current_server_provider", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a custom server provider
 */
async removeServerProvider(request: RemoveProviderRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_server_provider", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Test connectivity to the current server provider
 */
async testServerProviderConnectivity() : Promise<Result<ConnectivityStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_server_provider_connectivity") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get API URL for the current server provider
 */
async getServerProviderApiUrl() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_server_provider_api_url") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get identity URL for the current server provider
 */
async getServerProviderIdentityUrl() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_server_provider_identity_url") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get icons URL for the current server provider
 */
async getServerProviderIconsUrl() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_server_provider_icons_url") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get web vault URL for the current server provider
 */
async getServerProviderWebVaultUrl() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_server_provider_web_vault_url") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get notifications URL for the current server provider
 */
async getServerProviderNotificationsUrl() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_server_provider_notifications_url") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get events URL for the current server provider
 */
async getServerProviderEventsUrl() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_server_provider_events_url") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check biometric availability
 */
async checkBiometricAvailability() : Promise<Result<BiometricStatusResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_biometric_availability") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Authenticate with biometric
 */
async authenticateBiometric(request: BiometricAuthRequest) : Promise<Result<BiometricAuthResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("authenticate_biometric", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Setup biometric unlock (alternative implementation)
 */
async setupBiometricUnlockAlt(request: SetupBiometricRequest) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("setup_biometric_unlock_alt", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieve user key with biometric authentication
 */
async retrieveBiometricUserKey(request: RetrieveBiometricKeyRequest) : Promise<Result<RetrieveBiometricKeyResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retrieve_biometric_user_key", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete biometric unlock
 */
async deleteBiometricUnlock(userId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_biometric_unlock", { userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if biometric unlock is enabled
 */
async isBiometricUnlockEnabled(userId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_biometric_unlock_enabled", { userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get current settings
 */
async getSettings() : Promise<Result<Settings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save settings
 */
async saveSettings(request: SaveSettingsRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reset settings to defaults
 */
async resetSettings() : Promise<Result<Settings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Migrate legacy settings to current format
 */
async migrateLegacySettings(request: MigrateLegacySettingsRequest) : Promise<Result<Settings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("migrate_legacy_settings", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Request to add a new custom server provider
 */
export type AddCustomProviderRequest = { label: string; base_url: string }
/**
 * Request to add a new custom server provider with custom URLs
 */
export type AddCustomProviderWithUrlsRequest = { label: string; urls: ServerProviderUrls }
/**
 * Application error types
 */
export type AppError = { AuthenticationError: { message: string } } | { CryptographyError: { operation: string } } | { DatabaseError: { message: string } } | { NetworkError: { status: number; message: string } } | { StorageError: { message: string } } | { ValidationError: { field: string; message: string } } | { ConfigurationError: { message: string } } | { BiometricError: { message: string } } | { SyncError: { message: string } } | { InternalError: { message: string } }
export type BiometricAuthRequest = { prompt: string }
export type BiometricAuthResponse = { success: boolean }
export type BiometricStatusResponse = { status: string; available: boolean }
export type BiometricUnlockRequest = { user_id: string }
export type BiometricUnlockResponse = { success: boolean; user_key: number[] | null }
/**
 * Card cipher data
 */
export type CardView = { cardholder_name: string | null; brand: string | null; number: string | null; exp_month: string | null; exp_year: string | null; code: string | null }
/**
 * Cipher types
 */
export type CipherType = "Login" | "SecureNote" | "Card" | "Identity"
/**
 * Decrypted cipher view for frontend
 */
export type CipherView = { id: string; organization_id: string | null; folder_id: string | null; name: string; notes: string | null; cipher_type: CipherType; login: LoginView | null; secure_note: SecureNoteView | null; card: CardView | null; identity: IdentityView | null; favorite: boolean; reprompt: boolean; revision_date: string; created_date: string }
/**
 * Collection model
 */
export type Collection = { id: string; organization_id: string; name: string; external_id: string | null; revision_date: string }
/**
 * Connectivity test results
 */
export type ConnectivityStatus = { api_reachable: boolean; identity_reachable: boolean; overall_status: boolean }
export type DeleteCipherRequest = { cipher_id: string; user_id: string }
export type DeleteFolderRequest = { folder_id: string; user_id: string }
/**
 * Folder model
 */
export type Folder = { id: string; user_id: string; name: string; revision_date: string }
export type GetCiphersRequest = { user_id: string }
export type GetCollectionsRequest = { organization_id: string }
export type GetFoldersRequest = { user_id: string }
/**
 * Identity cipher data
 */
export type IdentityView = { title: string | null; first_name: string | null; middle_name: string | null; last_name: string | null; address1: string | null; address2: string | null; address3: string | null; city: string | null; state: string | null; postal_code: string | null; country: string | null; company: string | null; email: string | null; phone: string | null; ssn: string | null; username: string | null; passport_number: string | null; license_number: string | null }
export type KdfConfig = { kdf_type: number; iterations: number; memory: number | null; parallelism: number | null }
export type LoginRequest = { email: string; password: string; kdf_config: KdfConfig }
export type LoginResponse = { success: boolean; user_id: string; master_key: number[]; master_key_hash: string }
/**
 * Login URI data
 */
export type LoginUriView = { uri: string | null; match_type: number | null }
/**
 * Login cipher data
 */
export type LoginView = { username: string | null; password: string | null; totp: string | null; uris: LoginUriView[] }
export type MigrateLegacySettingsRequest = { legacy_settings: string }
export type PreloginRequest = { email: string }
export type PreloginResponse = { kdf: number; kdfIterations: number; kdfMemory: number | null; kdfParallelism: number | null }
/**
 * Request to remove a server provider
 */
export type RemoveProviderRequest = { provider_id: string }
export type RetrieveBiometricKeyRequest = { user_id: string; prompt: string }
export type RetrieveBiometricKeyResponse = { success: boolean; user_key: number[] | null }
export type SaveCipherRequest = { cipher: CipherView; user_id: string }
export type SaveFolderRequest = { folder: Folder }
export type SaveSettingsRequest = { settings: Settings }
export type SearchCiphersRequest = { query: string; user_id: string }
/**
 * Secure note cipher data
 */
export type SecureNoteView = { note_type: number }
/**
 * Server provider model
 */
export type ServerProvider = { id: string; provider_type: ServerProviderType; label: string; region: string | null; urls: ServerProviderUrls; created_at: string; updated_at: string }
/**
 * Server provider information for frontend
 */
export type ServerProviderInfo = { current_provider: ServerProvider | null; all_providers: ServerProvider[]; preset_providers: ServerProvider[]; custom_providers: ServerProvider[] }
/**
 * Server provider type
 */
export type ServerProviderType = "Preset" | "Custom"
/**
 * Server provider URLs configuration
 */
export type ServerProviderUrls = { base: string | null; api: string | null; identity: string | null; icons: string | null; web_vault: string | null; notifications: string | null; events: string | null; key_connector: string | null; scim: string | null }
/**
 * Request to set the current server provider
 */
export type SetCurrentProviderRequest = { provider_id: string }
/**
 * Settings model for application configuration
 */
export type Settings = { theme: string; language: string; vault_timeout: number; vault_timeout_action: string; biometric_unlock: boolean; clear_clipboard: number; minimize_to_tray: boolean; start_to_tray: boolean; auto_start: boolean; server_url: string | null }
export type SetupAccountRequest = { email: string; password: string; kdf_config: KdfConfig }
export type SetupAccountResponse = { user_id: string; master_key: number[]; master_key_hash: string; user_key: number[]; encrypted_user_key: number[]; public_key: number[]; encrypted_private_key: number[] }
export type SetupBiometricRequest = { user_id: string; user_key: number[] }
export type UnlockRequest = { user_id: string; password: string }
export type UnlockResponse = { success: boolean; master_key: number[] | null; user_key: number[] | null }
/**
 * Request to update an existing server provider
 */
export type UpdateProviderRequest = { provider_id: string; label: string | null; urls: ServerProviderUrls | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
