#[cfg(test)]
mod typescript_generation_tests {
    use std::fs;
    use std::path::Path;

    /// Test that the generated TypeScript file contains no 'any' types
    #[test]
    fn test_no_any_types_in_generated_typescript() {
        let typescript_file_path = "../src/lib/tauri-commands.ts";
        
        // Check if the file exists
        if !Path::new(typescript_file_path).exists() {
            panic!("TypeScript file not found. Run 'cargo run' first to generate types.");
        }

        let content = fs::read_to_string(typescript_file_path)
            .expect("Failed to read TypeScript file");

        // Define problematic patterns that should not exist
        let problematic_patterns = [
            "as any",
            ": any",
            "<any>",
            "Record<string, any>",
            "unknown as any",
        ];

        let mut issues = Vec::new();
        for (line_num, line) in content.lines().enumerate() {
            for pattern in &problematic_patterns {
                if line.contains(pattern) {
                    issues.push(format!(
                        "Line {}: Found '{}' in: {}",
                        line_num + 1,
                        pattern,
                        line.trim()
                    ));
                }
            }
        }

        if !issues.is_empty() {
            panic!(
                "Found {} 'any' type issues in generated TypeScript:\n{}",
                issues.len(),
                issues.join("\n")
            );
        }
    }

    /// Test that the generated TypeScript file has proper type-safe replacements
    #[test]
    fn test_proper_type_safe_replacements() {
        let typescript_file_path = "../src/lib/tauri-commands.ts";
        
        if !Path::new(typescript_file_path).exists() {
            panic!("TypeScript file not found. Run 'cargo run' first to generate types.");
        }

        let content = fs::read_to_string(typescript_file_path)
            .expect("Failed to read TypeScript file");

        // Check for expected type-safe patterns
        let expected_patterns = [
            "e as string",
            "Record<string, unknown>",
            "__EventObj__<unknown>",
            "Parameters<typeof window.listen>[1]",
            "Parameters<typeof TAURI_API_EVENT.listen>[1]",
            "(() => {}) as unknown",
        ];

        let mut found_patterns = Vec::new();
        for pattern in &expected_patterns {
            if content.contains(pattern) {
                found_patterns.push(*pattern);
            }
        }

        // We should find at least some of these patterns
        assert!(
            !found_patterns.is_empty(),
            "Expected to find type-safe patterns in generated TypeScript, but found none. \
             This might indicate the fixes are not being applied correctly."
        );

        println!("✅ Found type-safe patterns: {:?}", found_patterns);
    }

    /// Test that the TypeScript file has proper header
    #[test]
    fn test_typescript_file_header() {
        let typescript_file_path = "../src/lib/tauri-commands.ts";
        
        if !Path::new(typescript_file_path).exists() {
            panic!("TypeScript file not found. Run 'cargo run' first to generate types.");
        }

        let content = fs::read_to_string(typescript_file_path)
            .expect("Failed to read TypeScript file");

        // Check for proper header
        assert!(
            content.contains("// This file was generated by tauri-specta. Do not edit this file manually."),
            "TypeScript file should have proper generation header"
        );

        assert!(
            content.contains("// @ts-check"),
            "TypeScript file should have @ts-check directive"
        );

        assert!(
            content.contains("// This file uses strict TypeScript settings to ensure type safety."),
            "TypeScript file should have type safety notice"
        );
    }

    /// Test that all command functions are properly typed
    #[test]
    fn test_command_function_types() {
        let typescript_file_path = "../src/lib/tauri-commands.ts";
        
        if !Path::new(typescript_file_path).exists() {
            panic!("TypeScript file not found. Run 'cargo run' first to generate types.");
        }

        let content = fs::read_to_string(typescript_file_path)
            .expect("Failed to read TypeScript file");

        // Check that command functions have proper return types
        let command_patterns = [
            "Promise<Result<",
            "status: \"ok\"",
            "status: \"error\"",
        ];

        for pattern in &command_patterns {
            assert!(
                content.contains(pattern),
                "TypeScript file should contain proper command pattern: {}",
                pattern
            );
        }
    }

    /// Test that error types are properly defined
    #[test]
    fn test_error_types_defined() {
        let typescript_file_path = "../src/lib/tauri-commands.ts";
        
        if !Path::new(typescript_file_path).exists() {
            panic!("TypeScript file not found. Run 'cargo run' first to generate types.");
        }

        let content = fs::read_to_string(typescript_file_path)
            .expect("Failed to read TypeScript file");

        // Check that AppError type is properly defined
        assert!(
            content.contains("export type AppError"),
            "TypeScript file should export AppError type"
        );

        // Check that Result type is properly defined
        assert!(
            content.contains("export type Result<T, E>"),
            "TypeScript file should export Result type"
        );
    }

    /// Test file structure and exports
    #[test]
    fn test_file_structure() {
        let typescript_file_path = "../src/lib/tauri-commands.ts";
        
        if !Path::new(typescript_file_path).exists() {
            panic!("TypeScript file not found. Run 'cargo run' first to generate types.");
        }

        let content = fs::read_to_string(typescript_file_path)
            .expect("Failed to read TypeScript file");

        // Check for main exports
        assert!(
            content.contains("export const commands"),
            "TypeScript file should export commands object"
        );

        // Check that the file is not empty
        assert!(
            content.len() > 1000,
            "TypeScript file seems too small, might be incomplete"
        );

        // Check that it contains actual command definitions
        assert!(
            content.contains("async "),
            "TypeScript file should contain async command functions"
        );
    }
}
