mod api;
mod app_state;
mod commands;
mod crypto;
mod error;

pub mod logging;
mod middleware;
mod models;
mod services;
// mod specta_config; // Moving specta config directly into lib.rs
mod storage;

use app_state::AppState;
use tauri::Manager;
// Removed unused tracing imports since we're using log crate now

// Tauri-specta imports
use specta_typescript::Typescript;
use tauri_specta::{collect_commands, collect_events, Builder};

// Import commands with specta annotations
use crate::commands::auth::{
    change_master_password, lock_vault, login_with_password, logout, prelogin, refresh_token,
    setup_account, setup_biometric_unlock, unlock_with_biometric, unlock_with_password,
};
use crate::commands::biometric::{
    authenticate_biometric, check_biometric_availability, delete_biometric_unlock,
    is_biometric_unlock_enabled, retrieve_biometric_user_key, setup_biometric_unlock_alt,
};
use crate::commands::server_provider::{
    add_custom_server_provider, add_custom_server_provider_with_urls, get_all_server_providers,
    get_current_server_provider, get_server_provider_api_url, get_server_provider_events_url,
    get_server_provider_icons_url, get_server_provider_identity_url, get_server_provider_info,
    get_server_provider_notifications_url, get_server_provider_web_vault_url,
    remove_server_provider, set_current_server_provider, test_server_provider_connectivity,
    update_server_provider,
};
use crate::commands::settings::{
    get_settings, migrate_legacy_settings, reset_settings, save_settings,
};
use crate::commands::vault::{
    delete_cipher, delete_folder, get_all_ciphers, get_collections, get_folders, save_cipher,
    save_folder, search_ciphers,
};

/// Create TypeScript configuration with strict type safety
#[cfg(debug_assertions)]
fn create_typescript_config() -> Typescript {
    Typescript::default()
        .header("// This file was generated by tauri-specta. Do not edit this file manually.\n// @ts-check\n// This file uses strict TypeScript settings to ensure type safety.")
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Configure tauri-specta for type-safe commands
    let specta_builder = Builder::new()
        .commands(collect_commands![
            // Auth commands
            prelogin,
            login_with_password,
            unlock_with_password,
            setup_account,
            lock_vault,
            logout,
            refresh_token,
            change_master_password,
            setup_biometric_unlock,
            unlock_with_biometric,
            // Vault commands
            get_all_ciphers,
            save_cipher,
            delete_cipher,
            search_ciphers,
            get_folders,
            save_folder,
            delete_folder,
            get_collections,
            // Server provider commands
            get_all_server_providers,
            get_current_server_provider,
            get_server_provider_info,
            add_custom_server_provider,
            add_custom_server_provider_with_urls,
            update_server_provider,
            set_current_server_provider,
            remove_server_provider,
            test_server_provider_connectivity,
            get_server_provider_api_url,
            get_server_provider_identity_url,
            get_server_provider_icons_url,
            get_server_provider_web_vault_url,
            get_server_provider_notifications_url,
            get_server_provider_events_url,
            // Biometric commands
            check_biometric_availability,
            authenticate_biometric,
            setup_biometric_unlock_alt,
            retrieve_biometric_user_key,
            delete_biometric_unlock,
            is_biometric_unlock_enabled,
            // Settings commands
            get_settings,
            save_settings,
            reset_settings,
            migrate_legacy_settings,
        ])
        .events(collect_events![]);

    // Export TypeScript types in debug mode with strict type safety
    #[cfg(debug_assertions)]
    {
        let typescript_config = create_typescript_config();

        specta_builder
            .export(typescript_config, "../src/lib/tauri-commands.ts")
            .expect("Failed to export TypeScript bindings");

        println!("✅ TypeScript bindings exported successfully with type-safe fixes applied!");
    }

    tauri::Builder::default()
        .plugin(
            tauri_plugin_log::Builder::default()
                .level(if cfg!(debug_assertions) {
                    log::LevelFilter::Debug
                } else {
                    log::LevelFilter::Info
                })
                .build(),
        )
        .setup(|app| {
            // Initialize our enhanced logging system after tauri-plugin-log
            match logging::init_enhanced_logging() {
                Ok(_) => {
                    log::info!("[startup] Enhanced logging system initialized successfully");
                }
                Err(e) => {
                    log::error!("Failed to initialize enhanced logging: {}", e);
                }
            }

            logging::log_startup();

            // Initialize application state asynchronously
            let app_handle = app.handle().clone();
            tauri::async_runtime::spawn(async move {
                log::info!("[startup] Starting application state initialization");
                let start_time = std::time::Instant::now();

                match AppState::new(app_handle.clone()).await {
                    Ok(state) => {
                        let duration_ms = start_time.elapsed().as_millis() as u64;
                        app_handle.manage(state);
                        log::info!(
                            "[startup] Application state initialized successfully in {}ms",
                            duration_ms
                        );
                    }
                    Err(e) => {
                        let duration_ms = start_time.elapsed().as_millis() as u64;
                        log::error!(
                            "[startup] Failed to initialize application state after {}ms: {}",
                            duration_ms,
                            e
                        );
                    }
                }
            });

            Ok(())
        })
        // Security and storage plugins
        .plugin(
            tauri_plugin_stronghold::Builder::new(|password| {
                // Simple password hashing for stronghold - in production use proper key derivation
                use sha2::{Digest, Sha256};
                let mut hasher = Sha256::new();
                hasher.update(password.as_bytes());
                hasher.finalize().to_vec()
            })
            .build(),
        )
        // Database management is now handled directly in AppDatabase
        .plugin(tauri_plugin_store::Builder::default().build())
        // System integration plugins
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_os::init())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_http::init())
        // Application behavior plugins
        .plugin(tauri_plugin_window_state::Builder::default().build())
        .plugin(tauri_plugin_single_instance::init(|app, argv, cwd| {
            println!("{}, {argv:?}, {cwd}", app.package_info().name);
        }))
        .plugin(tauri_plugin_updater::Builder::new().build())
        // Legacy opener plugin
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(specta_builder.invoke_handler())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

// Production configuration
pub fn is_production() -> bool {
    cfg!(not(debug_assertions))
}

pub fn should_enable_crypto_cache() -> bool {
    true // Always enable for performance benefits
}

pub fn should_enable_error_monitoring() -> bool {
    true // Always enable for critical issue detection
}

// Migration validation is now handled in the database migration runner
